### ISSUE TITLE
File not found "props/server.properties"

### ISSUE THREAD

**Issue by anujbhan** [airavata-courses/TeamAlpha#5] opened 2016-01-31 19:51 UTC
```
at com.teamAlpha.airavata.facade.Main.main(Main.java:29)
Caused by: java.io.FileNotFoundException: props\server.properties
```

The above error pops up when trying to run the maven built jar file

**Comment by ajinkya-dhamnaskar** [comment] 2016-02-01 01:41
We have to change forward slash (/) or backward slash() depending on which system the jar is being executed. For windows use \, and for Linux use /.

**Comment by patel99** [comment] 2016-02-01 08:04
Anuj,

I think you are running jar from command prompt. If that is the case, please copy 'props' folder(which is in the 'Airavata_Remote_Job_Runner' directory) to the same directory as the jar file. It is giving you this error as it uses a relative path. 
We should have put this in Instructions. Thanks for pointing this out.
If there are any further error then let us know. And if the issue is resolved then kindly close this issue.

**Closed as completed** 2016-02-22 18:15 UTC
